### ISSUE TITLE
Does not compile on Pop!_OS 21.04 with 5.11.0 kernel

### ISSUE THREAD

**Issue by agentelinux** [leifliddy/macbook12-bluetooth-driver#13]
Error log is as follows:

```

linux-5.11/drivers/bluetooth/hci_vhci.c
make -C /lib/modules/5.11.0-7620-generic/build M=/home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0 modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-7620-generic'
  CC [M]  /home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ldisc.o
/home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ldisc.c: In function ‘hci_uart_init’:
/home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ldisc.c:836:23: error: assignment to ‘ssize_t (*)(struct tty_struct *, struct file *, unsigned char *, size_t,  void **, long unsigned int)’ {aka ‘long int (*)(struct tty_struct *, struct file *, unsigned char *, long unsigned int,  void **, long unsigned int)’} from incompatible pointer type ‘ssize_t (*)(struct tty_struct *, struct file *, unsigned char *, size_t)’ {aka ‘long int (*)(struct tty_struct *, struct file *, unsigned char *, long unsigned int)’} [-Werror=incompatible-pointer-types]
  836 |  hci_uart_ldisc.read  = hci_uart_tty_read;
      |                       ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:287: /home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ldisc.o] Error 1
make[1]: *** [Makefile:1848: /home/krishna/Downloads/dev/macbook12-bluetooth-driver/build/bluetooth-5.11.0] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-7620-generic'
make: *** [Makefile:19: all] Error 2
cp hci_uart.ko /lib/modules/5.11.0-7620-generic/updates
cp: cannot stat 'hci_uart.ko': No such file or directory
make: *** [Makefile:26: install] Error 1

contents of /lib/modules/5.11.0-7620-generic/updates
total 4
drwxr-xr-x 2 root root 4096 Jun 29 19:12 dkms

```
 ls -l /lib/modules/5.11.0-7620-generic/build/
```
krishna@pop-os:~/Downloads/dev/macbook12-bluetooth-driver$ ls -l /lib/modules/5.11.0-7620-generic/build/
total 1724
drwxr-xr-x 3 root root    4096 Jun 29 19:01 arch
lrwxrwxrwx 1 root root      34 Jun 22 13:35 block -> ../linux-headers-5.11.0-7620/block
lrwxrwxrwx 1 root root      34 Jun 22 13:35 certs -> ../linux-headers-5.11.0-7620/certs
lrwxrwxrwx 1 root root      35 Jun 22 13:35 crypto -> ../linux-headers-5.11.0-7620/crypto
lrwxrwxrwx 1 root root      42 Jun 22 13:35 Documentation -> ../linux-headers-5.11.0-7620/Documentation
lrwxrwxrwx 1 root root      36 Jun 22 13:35 drivers -> ../linux-headers-5.11.0-7620/drivers
lrwxrwxrwx 1 root root      31 Jun 22 13:35 fs -> ../linux-headers-5.11.0-7620/fs
drwxr-xr-x 4 root root    4096 Jun 29 19:01 include
lrwxrwxrwx 1 root root      33 Jun 22 13:35 init -> ../linux-headers-5.11.0-7620/init
lrwxrwxrwx 1 root root      32 Jun 22 13:35 ipc -> ../linux-headers-5.11.0-7620/ipc
lrwxrwxrwx 1 root root      35 Jun 22 13:35 Kbuild -> ../linux-headers-5.11.0-7620/Kbuild
lrwxrwxrwx 1 root root      36 Jun 22 13:35 Kconfig -> ../linux-headers-5.11.0-7620/Kconfig
drwxr-xr-x 2 root root    4096 Jun 29 19:01 kernel
lrwxrwxrwx 1 root root      32 Jun 22 13:35 lib -> ../linux-headers-5.11.0-7620/lib
lrwxrwxrwx 1 root root      37 Jun 22 13:35 Makefile -> ../linux-headers-5.11.0-7620/Makefile
lrwxrwxrwx 1 root root      31 Jun 22 13:35 mm -> ../linux-headers-5.11.0-7620/mm
-rw-r--r-- 1 root root 1744328 Jun 22 13:35 Module.symvers
lrwxrwxrwx 1 root root      32 Jun 22 13:35 net -> ../linux-headers-5.11.0-7620/net
lrwxrwxrwx 1 root root      39 Jun 22 13:35 rebuild.sh -> ../linux-headers-5.11.0-7620/rebuild.sh
lrwxrwxrwx 1 root root      41 Jun 22 13:35 reinstall.sh -> ../linux-headers-5.11.0-7620/reinstall.sh
lrwxrwxrwx 1 root root      39 Jun 22 13:35 remotes.sh -> ../linux-headers-5.11.0-7620/remotes.sh
lrwxrwxrwx 1 root root      36 Jun 22 13:35 samples -> ../linux-headers-5.11.0-7620/samples
drwxr-xr-x 7 root root    4096 Jun 29 19:01 scripts
lrwxrwxrwx 1 root root      37 Jun 22 13:35 security -> ../linux-headers-5.11.0-7620/security
lrwxrwxrwx 1 root root      34 Jun 22 13:35 sound -> ../linux-headers-5.11.0-7620/sound
lrwxrwxrwx 1 root root      40 Jun 22 13:35 system76.sh -> ../linux-headers-5.11.0-7620/system76.sh
drwxr-xr-x 4 root root    4096 Jun 29 19:01 tools
lrwxrwxrwx 1 root root      35 Jun 22 13:35 ubuntu -> ../linux-headers-5.11.0-7620/ubuntu
lrwxrwxrwx 1 root root      32 Jun 22 13:35 usr -> ../linux-headers-5.11.0-7620/usr
lrwxrwxrwx 1 root root      33 Jun 22 13:35 virt -> ../linux-headers-5.11.0-7620/virt


```
Tks :-)

**Comment by leifliddy** [comment]
Something got jacked up somewhere. I was able to replicate this issue on ubuntu. 
It could be related to the patches that ubuntu applied to the 5.11.0 kernel
To be honest, I don't really feel like doing a deep dive into the specifics.

The "fix" is to modify the following in **hci_ldisc.c**

change:
```
static ssize_t hci_uart_tty_read(struct tty_struct *tty, struct file *file,
				 unsigned char __user *buf, size_t nr)
```
to
```
static ssize_t hci_uart_tty_read(struct tty_struct *tty, struct file *file,
				 unsigned char __user *buf, size_t nr,
				 void **cookie, unsigned long offset)
```

It should then compile no problem
```
root@ubuntu:~/macbook12-bluetooth-driver/build/bluetooth-5.11.0# make
make -C /lib/modules/5.11.0-22-generic/build M=/root/macbook12-bluetooth-driver/build/bluetooth-5.11.0 modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-22-generic'
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ldisc.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_serdev.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_h4.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_bcsp.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ll.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ath.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_h5.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_intel.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_bcm.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_qca.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_ag6xx.o
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_mrvl.o
  LD [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_uart.o
  MODPOST /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/Module.symvers
  CC [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_uart.mod.o
  LD [M]  /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_uart.ko
  BTF [M] /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_uart.ko
Skipping BTF generation for /root/macbook12-bluetooth-driver/build/bluetooth-5.11.0/hci_uart.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-22-generic'
strip --strip-debug hci_uart.ko

root@ubuntu:~/macbook12-bluetooth-driver/build/bluetooth-5.11.0# make install
cp hci_uart.ko /lib/modules/5.11.0-22-generic/updates
depmod -a
```

**Comment by siyan4** [comment]
It works after I add this into the script before 'mv bluetooth $bluetooth_dir', thanks!

sed -i 's/size_t nr/size_t nt, void **cookie, unsigned long offset/' bluetooth/hci_ldisc.c

**Comment by leifliddy** [comment]
Nice! BTW, you won't need to do this once you hit kernel 5.11.3
