### ISSUE TITLE
Does not compile on Manjaro with 5.10.7-3 kernel

### ISSUE THREAD

**Issue by alvitg** [leifliddy/macbook12-bluetooth-driver#11]
Fails to compile on Manjaro with 5.10.7-3 kernel.

Error log is as following:

CC [M]  /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.o
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c: In function 'bcm_setup':
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:542:35: error: passing argument 2 of 'btbcm_initialize' from incompatible pointer type [-Werror=incompatible-pointer-types]
  542 |  err = btbcm_initialize(hu->hdev, fw_name, sizeof(fw_name), false);
      |                                   ^~~~~~~
      |                                   |
      |                                   char *
In file included from /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:46:
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/btbcm.h:65:50: note: expected 'bool *' {aka '_Bool *'} but argument is of type 'char *'
   65 | int btbcm_initialize(struct hci_dev *hdev, bool *fw_load_done);
      |                                            ~~~~~~^~~~~~~~~~~~
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:542:8: error: too many arguments to function 'btbcm_initialize'
  542 |  err = btbcm_initialize(hu->hdev, fw_name, sizeof(fw_name), false);
      |        ^~~~~~~~~~~~~~~~
In file included from /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:46:
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/btbcm.h:65:5: note: declared here
   65 | int btbcm_initialize(struct hci_dev *hdev, bool *fw_load_done);
      |     ^~~~~~~~~~~~~~~~
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:586:8: error: too few arguments to function 'btbcm_finalize'
  586 |  err = btbcm_finalize(hu->hdev);
      |        ^~~~~~~~~~~~~~
In file included from /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.c:46:
/root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/btbcm.h:66:5: note: declared here
   66 | int btbcm_finalize(struct hci_dev *hdev, bool *fw_load_done);
      |     ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7/hci_bcm.o] Error 1
make[1]: *** [Makefile:1805: /root/drv/macbook12-bluetooth-driver/build/bluetooth-5.10.7] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.7-3-MANJARO/build'

**Comment by leifliddy** [comment]
Do you have the kernel 5.10 headers installed?

**Comment by alvitg** [comment]
Yes, I have. It is the ninth object in Makefile which causes the problem. Previous eight compile successfully. I think it would be impossible in case of kernel headers absence. snd_hda_macbookpro compiles successfully also, as well as three dkms modules.

**Comment by alvitg** [comment]
❯ uname -r
5.10.7-3-MANJARO
❯ ls -la /usr/lib/modules/$(uname -r)/build
итого 68892
drwxr-xr-x  22 root root     4096 янв 19 17:46 .
drwxr-xr-x   6 root root     4096 янв 19 17:48 ..
drwxr-xr-x   3 root root     4096 янв 19 17:46 arch
drwxr-xr-x   3 root root     4096 янв 19 17:46 block
drwxr-xr-x   2 root root     4096 янв 19 17:46 certs
-rw-r--r--   1 root root   232478 янв 16 02:10 .config
drwxr-xr-x   4 root root     4096 янв 19 17:46 crypto
drwxr-xr-x 134 root root     4096 янв 19 17:46 drivers
drwxr-xr-x  68 root root     4096 янв 19 17:46 fs
drwxr-xr-x  31 root root     4096 янв 19 17:07 include
drwxr-xr-x   2 root root     4096 янв 19 17:46 init
-rw-r--r--   1 root root      555 янв 16 02:10 Kconfig
drwxr-xr-x  11 root root     4096 янв 19 17:46 kernel
drwxr-xr-x   8 root root     4096 янв 19 17:46 lib
-rw-r--r--   1 root root    64376 янв 16 02:10 Makefile
drwxr-xr-x   2 root root     4096 янв 19 17:46 mm
-rw-r--r--   1 root root  1658725 янв 16 02:10 Module.symvers
drwxr-xr-x  64 root root     4096 янв 19 17:46 net
drwxr-xr-x   2 root root     4096 янв 19 17:46 samples
drwxr-xr-x  17 root root     4096 янв 19 17:46 scripts
drwxr-xr-x  12 root root     4096 янв 19 17:46 security
drwxr-xr-x  25 root root     4096 янв 19 17:46 sound
drwxr-xr-x   2 root root     4096 янв 16 02:10 .tmp_versions
drwxr-xr-x   3 root root     4096 янв 19 17:07 tools
drwxr-xr-x   2 root root     4096 янв 19 17:46 usr
drwxr-xr-x   4 root root     4096 янв 19 17:07 virt
-rw-r--r--   1 root root 76108128 янв 16 02:10 vmlinux

**Comment by alvitg** [comment]
Additionally, gcc 10.2.0 is used as system compiler.

**Comment by leifliddy** [comment]
Odd, I'm seeing the same error on Fedora now. I don't remember seeing that before. I'll look at this a bit later today.

**Comment by leifliddy** [comment]
Ahhh, ok so it will compile normally with the original ```hci_bcm.c``` file, but not with the modified one. Ok, this shouldn't be too hard to sort out.

**Comment by leifliddy** [comment]
Ok, so ```hci_bcm.c``` has been significantly modified since kernel 5.9
The modifications applied with ```install.bluetooth.sh``` are no longer valid and end up butchering ```hci.bcm.c```
But...bluetooth seems to be working fine on my system running the stock 5.10 kernel (macbook9,1) 
I'll do some testing later tonight, need to power it on and off a few times to ensure that it's stable.
Does bluetooth work for you w/ the stock kernel?
If not, then the patch needed for kernel 5.10 needs a complete rewrite.

**Comment by alvitg** [comment]
No, bluetooth is not working with stock kernel on macbookpro13,1.

Here are some messages:

[mbookpro-avg ~]# dmesg | grep Bluetooth
[    4.410973] Bluetooth: Core ver 2.22
[    4.410993] Bluetooth: HCI device and connection manager initialized
[    4.410996] Bluetooth: HCI socket layer initialized
[    4.410998] Bluetooth: L2CAP socket layer initialized
[    4.411002] Bluetooth: SCO socket layer initialized
[    4.685513] Bluetooth: HCI UART driver ver 2.3
[    4.685514] Bluetooth: HCI UART protocol H4 registered
[    4.685515] Bluetooth: HCI UART protocol BCSP registered
[    4.685533] Bluetooth: HCI UART protocol LL registered
[    4.685533] Bluetooth: HCI UART protocol ATH3K registered
[    4.685541] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    4.685574] Bluetooth: HCI UART protocol Intel registered
[    4.685613] Bluetooth: HCI UART protocol Broadcom registered
[    4.685619] Bluetooth: HCI UART protocol QCA registered
[    4.685620] Bluetooth: HCI UART protocol AG6XX registered
[    4.685626] Bluetooth: HCI UART protocol Marvell registered
[    5.358225] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    5.358226] Bluetooth: BNEP filters: protocol multicast
[    5.358230] Bluetooth: BNEP socket layer initialized
[    7.198473] Bluetooth: hci0: command 0xfc18 tx timeout
[   15.305485] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   15.305495] Bluetooth: hci0: Failed to set baudrate
[   17.438485] Bluetooth: hci0: command 0x0c03 tx timeout
[   25.331975] Bluetooth: hci0: BCM: Reset failed (-110)

[mbookpro-avg ~]# dmesg | grep hci
[    4.866106] hci_uart_bcm serial0-0: Unexpected ACPI gpio_int_idx: -1
[    4.866108] hci_uart_bcm serial0-0: Unexpected number of ACPI GPIOs: 0
[    4.866113] hci_uart_bcm serial0-0: No reset resource, using default baud rate
[    7.198473] Bluetooth: hci0: command 0xfc18 tx timeout
[   15.305485] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   15.305495] Bluetooth: hci0: Failed to set baudrate
[   17.438485] Bluetooth: hci0: command 0x0c03 tx timeout
[   25.331975] Bluetooth: hci0: BCM: Reset failed (-110)

**Comment by leifliddy** [comment]
@alvitg Damn, there was a typo in a regular expression I was using. Ok, I've sorted it out -- the module should compile now.
Could you please test it out when you get a chance?

**Comment by alvitg** [comment]
Great! It is compiling and working now. Thanks a lot!
